# Exported from Render on 2025-10-18T14:50:13Z
version: "1"
services:
- type: web
  name: unicheck-api
  runtime: node
  repo: https://github.com/Edutobliv/unicheck
  plan: free
  envVars:
  - key: NPM_CONFIG_LOGLEVEL
    sync: false
  - key: NPM_CONFIG_FUND
    sync: false
  - key: NPM_CONFIG_AUDIT
    sync: false
  - key: NODE_ENV
    sync: false
  - key: AVATAR_BUCKET
    sync: false
  - key: SUPABASE_SERVICE_ROLE
    sync: false
  - key: SUPABASE_URL
    sync: false
  - key: JWT_SECRET
    sync: false
  - key: DATABASE_URL
    sync: false
  region: oregon
  buildCommand: npm ci --omit=dev
  startCommand: npm start
  healthCheckPath: /health
  autoDeployTrigger: commit
  rootDir: api_carnet
