services:
  - type: web
    name: unicheck-api
    env: node
    plan: free
    rootDir: api_carnet
    buildCommand: npm ci --omit=dev
    startCommand: npm start
    autoDeploy: true
    healthCheckPath: /health
    envVars:
      # Provide placeholders so the blueprint validates; set real values in the Render dashboard after creation
      - key: DATABASE_URL
        value: ""
      - key: JWT_SECRET
        generateValue: true
      - key: SUPABASE_URL
        value: ""
      - key: SUPABASE_SERVICE_ROLE
        value: ""
      - key: AVATAR_BUCKET
        value: avatars
      - key: NODE_ENV
        value: production
      - key: NPM_CONFIG_AUDIT
        value: "false"
      - key: NPM_CONFIG_FUND
        value: "false"
      - key: NPM_CONFIG_LOGLEVEL
        value: error
      # Optional: restrict who can register/login by email domain
      # - key: ALLOWED_EMAIL_DOMAINS
      #   value: example.edu
